main:
  - name: Home
    url: ""
    weight: 1
  - name: SwipeGallery
    url: "#service"
    weight: 2
  - name: Img/TextLists
    url: "#resume"
    weight: 3
  - name: AboutBlurb
    url: "#about"
    weight: 4
  - name: ProductSpotlight
    url: "#product"
    weight: 5
  - name: Testimonials/Quotes
    url: "#testimonial"
    weight: 6
  - name: Blog
    url: "#blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: IndividualProducts
    url: "product"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
