titleSeparator: '-'
titleAddition: Sub-Title
description: >-
  description
images:
  - favicon.ico
ogLocale: en_US
titleHome: HomeTitle
twitterSite: '@twitter_alias'
twitterCreator: '@twitter_alias'
schemaType: Organization
schemaName: SchemaName
schemaAuthor: J.Redd Robinson
schemaAuthorTwitter: 'https://twitter.com/'
schemaAuthorLinkedIn: 'https://www.linkedin.com/'
schemaAuthorGitHub: 'https://github.com/drpdead'
schemaLocale: en-US
schemaLogo: logo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: schema.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: 'https://twitter.com/'
schemaLinkedIn: ''
schemaGitHub: 'https://github.com/drpdead/Hugo-Corporio'
themeColor: 'red'
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: '320'
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - '480'
  - '720'
  - '1080'
  - '1280'
  - '1600'
  - '2048'
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: false
alertDismissable: true
alertText: >-
  Alert at top of main page. Can include HTML <a href="https://mozilla.com/html">tags</a>
blogPageURL: blog
contactLink: contact
copyright: All right reserved copyright © dropdeaddesigns 2024
footerLogo: images/site-navigation/logo.png
footerContact:
  topTitle: Top Title
  title: Lower Title below Top Title
  button: HomeButtonText
fabformURL: 'https://fabform.io/f/JpTXRUa'
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/site-navigation/logo.png
address:
  address: '555 Main St..'
  email: info@dropdeaddesigns.com
  openingHours: Open from 10am to 6pm (close at 5pm Sundays)
  phone: (+1) 555-555-2774
map:
  APIkey: YOUR GOOGLE MAP API
  latitude: '23.7783741'
  longitude: '90.3746808'
  pinImage: images/pin.png
social:
  - icon: fa-facebook-official
    url: 'https://www.facebook.com/'
    weight: 1
  - icon: fa-linkedin-square
    url: 'https://www.linkedin.com/'
    weight: 2
  - icon: fa-pinterest-square
    url: 'https://www.pinterest.com/'
    weight: 3
  - icon: fa-twitter-square
    url: 'https://twitter.com/'
    weight: 4
_template: parameters_template
